irc_details:
    address: "irc.torrentleech.org"
    port: 7011
    nickname: "JacksPythonBot"
    realname: "JacksBot"
    announce_channel: "#tlannounces"

download:
    directory: ""
    rsskey: ""

filters:
     TV:
         match: [".*"]
         subcategory: ["Episodes HD"]
     Movies:
         match: [".*"]
         subcategory: ["HD"]

headers:
    User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:37.0) Gecko/20100101 Firefox/37.0
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
    Accept-Encoding: gzip, deflate
    Accept-Language: en-GB,en;q=0.5
    Connection: keep-alive
